# @package _global_
model:
  id: vae
  name: VAEModel
  block_size: 1
  num_bits: ???
  embed_dim: ???

schedulers:
  beta: ???

dists:
  x_dist:
    name: ${dataset.dist_name}
    shape: ${dataset.shape}
    param_shape: ${dataset.param_shape}
  latent_dist:
    name: DiagonalGaussian
    shape:
      - ${model.block_size}
      - ${model.embed_dim}
    param_shape:
      - ${model.embed_dim}

networks:
  recognition_model:
    nn: ${nn.ffwd_recognition_model}    
    input_dists:
      x: x_dist
    output_dists:
      latent: latent_dist

  generative_model:
    nn: ${nn.generative_model}
    input_dists:
      latent: latent_dist
    output_dists:
      x: x_dist

optimizers:
  vae_opt:
    params: [recognition_model, generative_model]
    type: adamw
    lr_scheduler:
      type: constant_schedule
      value: 3e-4
    other:
      grad_clip: 1.0
      apply_if_finite: 100
