# @package _global_
model:
  num_bits: 576

dataset:
  id: cifar
  name: CIFARDataset
  in_memory: true
  sampler:
    name: DefaultSampler

  height: 32
  width: 32
  channels: 3
  scaler_mode: data # online or data
  scaler_type: standardize # standardize or normalize
  num_classes: 10
  include_labels: False

  dist_name: DiagonalGaussian
  shape:
    - ${dataset.height}
    - ${dataset.width}
    - ${dataset.channels}
  param_shape: ${dataset.shape}

job:
  start_checkpoint: null
  start_checkpoint_idx: 1
  checkpoint_overrides: []
  total_nsteps: 250000
  print_frequency_nsteps: 500
  wandb_inexpensive_frequency_nsteps: 500
  wandb_expensive_frequency_nsteps: 5000
  validation_frequency_nsteps: 5000
  checkpoint_frequency_nsteps: 50000

train:
  seed: 0
  batch_size: 256
  num_workers: 1

test:
  batch_size: 50 # should be divisible by 10,000
  num_workers: ${train.num_workers}