# @package _global_
model:
  num_bits: 640

dataset:
  id: lafan
  name: LAFANDataset
  in_memory: true # only supports in_memory!
  length: ${trajectory.input_len}
  channels: ???
  scaler_mode: data
  scaler_type: standardize # standardize or normalize
  dist_name: ???
  shape:
    - ${dataset.length}
    - ${dataset.channels}
  param_shape: ${dataset.shape}
  num_train: 1000

trajectory:
  input_len: 32

dists:
  x_dist:
    name: DiagonalGaussianConstantVariance
    x_var_prior: 0.25

job:
  checkpoint_overrides: []
  start_checkpoint_idx: -1
  total_nsteps: 250000
  print_frequency_nsteps: 500
  wandb_inexpensive_frequency_nsteps: 500
  wandb_expensive_frequency_nsteps: 5000
  validation_frequency_nsteps: 5000
  checkpoint_frequency_nsteps: 50000

train:
  seed: 0
  batch_size: 256
  num_workers: 1

test:
  num_val_samples: 10000
  batch_size: 200
