# @package _global_
model:
  block_size: 1024
  vocab_size: 1024
  embed_dim: 128

schedulers:
  beta:
    type: auto_exp_decay
    total_nsteps: ${job.total_nsteps}
    init_value: 50.0
    end_value: 1.0
    end_pct: 1.0
  temperature:
    type: auto_exp_decay
    total_nsteps: ${job.total_nsteps}
    init_value: 1.0
    end_value: 0.75
    end_pct: 1.0

optimizers:
  vae_opt:
    lr_scheduler:
      # type: cosine_decay_schedule
      # init_value: 1e-4
      # decay_steps: ${job.total_nsteps}
      # alpha: 0.1
      type: constant_schedule
      value: 1e-4

job:
  start_checkpoint: null
  start_checkpoint_idx: -1
